name: Test Craig

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run TypeScript check
      run: npx tsc --noEmit

    - name: Build frontend
      run: npm run build

    - name: Test frontend build
      run: |
        if [ ! -f "dist/index.html" ]; then
          echo "Frontend build failed - index.html not found"
          exit 1
        fi
        echo "Frontend build successful"

  test-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Check Rust code
      working-directory: src-tauri
      run: |
        cargo check
        cargo clippy -- -D warnings
        cargo fmt -- --check

    - name: Test Rust build
      working-directory: src-tauri
      run: cargo build --release

  test-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Test Docker build
      run: |
        docker build -f Dockerfile.dev -t craig-dev-test .
        echo "Docker build successful"

    - name: Test Docker compose
      run: |
        docker-compose config
        echo "Docker compose configuration valid"